server:
  port: 9090
  context-path: /apigateway

spring:
  application:
    name: ZUULAPIGATEWAY-SERVICE

zuul:
  routes:
    CUSTOMER-SERVICE:
      path: /customer/**
      strip-prefix: false
      service-id:
     # url : http://localhost:9091/
    ORDER-SERVICE:
      path: /order/**
      strip-prefix: false
      #url: http://localhost:9092/
      service-id:
  prefix: /service


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8500/eureka/



ribbon:
  ReadTimeout:200000
  SocketTimeout:200000
